
/**
* LinkExchangeSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LinkExchangeSystem.idl
* sobota, 12 grudnia 2015 19:37:10 CET
*/

public interface LinkExchangeSystem extends LinkExchangeSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LinkExchangeSystem
