
/**
* LinkExchangeSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LinkExchangeSystem.idl
* sobota, 12 grudnia 2015 19:37:10 CET
*/

public interface LinkExchangeSystemOperations 
{
  void register (String username, org.omg.CORBA.IntHolder userID);
  void addLink (int userID, String link, org.omg.CORBA.IntHolder linkID);
  boolean linkRemove (int userID, int linkID);
  boolean publishLink (int userID, int linkID);
  String[] getLinks (int userID);
} // interface LinkExchangeSystemOperations
