
/**
* LinkExchangeSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LinkExchangeSystem.idl
* Saturday, December 12, 2015 2:20:33 PM CET
*/

public interface LinkExchangeSystem extends LinkExchangeSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LinkExchangeSystem
