
/**
* LinkExchangeSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LinkExchangeSystem.idl
* Saturday, December 12, 2015 2:44:34 PM CET
*/

public interface LinkExchangeSystemOperations 
{
  void register (String username, org.omg.CORBA.IntHolder userID);
  void addLink (int userID, String link, org.omg.CORBA.IntHolder linkID);
  boolean linkRemove (int userID, int linkID);
  boolean publishLink (int userID, int linkID);
  String[] getLinks (int userID);
} // interface LinkExchangeSystemOperations
